### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wmyers**
Clarifying the new `development` setting for the server tools instance. We have `local`, `development`, `staging` and `production` environments configured with `NODE_ENV`

### CODE REVIEW

**Comment by halt-hammerzeit** [comment]
Oh.
So, should the explicit `.development()` method be returned back to the API?

**Comment by wmyers** [comment]
I think it's better to infer it from `NODE_ENV`, and it's almost completely backwards compatible. The only gotcha could be if someone set `NODE_ENV` to `production` but also defined `.development(true)` on the server instance - which would be wrong but could happen.

I guess you could output the actual value of `options.development` in the deprecation message to be super-clear - can knock-up another PR if you think it's a good idea

**Comment by wmyers** [comment]
hmm just noticed this further down `source/index.js`:

```
// ensure this is development mode
		if (!this.options.development)
		{
			throw new Error('.refresh() called in production mode. Did you forget to call .development() method on your webpack-isomorphic-tools server instance?')
		}
```

**Comment by halt-hammerzeit** [comment]
@wmyers Yeah, that's a good idea. I think I'll add the proper error message.

> hmm just noticed this further down source/index.js:

Oh, that's another one, thx

**Pull request merged**
