### PR TITLE
css-loader detect support pnpm or npminstall link style

### PR DESCRIPTION
**Pull request by fengmk2**
module.name will be:

- npminstall: `./~/.npminstall/css-loader/0.23.1/css-loader?modules`
- pnpm: `./~/.store/css-loader@0.23.1/_?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!./~/.store/autoprefixer-loader@3.2.0/_?browsers=last 2 version!./~/.store/sass-loader@3.2.0/_?outputStyle=expanded&sourceMap!./src/components/SurveyForm/SurveyForm.scss
`

---

```bash
$ ll node_modules/css-loader
node_modules/css-loader@ -> .store/css-loader@0.23.1/_

$ ll node_modules/webpack-isomorphic-tools
node_modules/webpack-isomorphic-tools@ -> .store/webpack-isomorphic-tools@2.2.44/_
```

### CODE REVIEW

**Comment by fengmk2** [comment]
- pnpm: https://github.com/rstacruz/pnpm
- npminstall: https://github.com/cnpm/npminstall

**Comment by halt-hammerzeit** [comment]
What if we change it to:

```js
const css_loader = module.name.split('!')[0]
return regular_expression.test(module.name) && (css_loader.indexOf('./~/css-loader') === 0 || css_loader.indexOf('./~/.npminstall/css-loader') === 0 || css_loader.indexOf('./~/.store/css-loader') === 0))
```

Do you think this will work?

**Comment by fengmk2** [comment]
Yep, I will change it.

**Comment by fengmk2** [comment]
@halt-hammerzeit fixed

**Comment by halt-hammerzeit** [comment]
```
/home/travis/build/halt-hammerzeit/webpack-isomorphic-tools/node_modules/babel-core/lib/transformation/file/index.js:671
      throw err;
            ^
SyntaxError: /home/travis/build/halt-hammerzeit/webpack-isomorphic-tools/source/plugin/plugin.js: Unexpected token (207:203)
{
	const css_loader = module.name.split('!')[0]
	return regular_expression.test(module.name) && (css_loader.indexOf('./~/css-loader') === 0 || css_loader.indexOf('./~/.npminstall/css-loader') === 0 || css_loader.indexOf('./~/.store/css-loader') === 0))
```

Remove the extra bracket at the end.

**Comment by fengmk2** [comment]
@halt-hammerzeit sorry for reply late, fixed now.

**Comment by halt-hammerzeit** [comment]
Done `webpack-isomorphic-tools@2.2.45`
Check that it works.

**Comment by fengmk2** [comment]
Thanks! `react-redux-universal-hot-example` is worked!

**Comment by halt-hammerzeit** [comment]
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example

**Pull request merged**
