### PR TITLE
update

### PR DESCRIPTION
**Pull request by Bartekus**
Upgrade babel to v6 & webpack to v2, as well as all other modules to most current versions.
All test pass except for the last one (camelCase).
Additional modification might be necessery.

### CODE REVIEW

**Comment by halt-hammerzeit** [comment]
@Bartekus Thanks, merging this in.
The test is failing because of old Node.js used in Travis, I'll bump the version.
I'll see if I can cut down on `devDependencies` too.

**Comment by halt-hammerzeit** [comment]
About the preset though: i'm not sure if demanding Node.js 5.0 is the right thing to do assuming the "LTS" and the "officially recommended" release is still 4.x
https://nodejs.org/en/
So I'll change the preset to Node 4.x

**Comment by halt-hammerzeit** [comment]
Fixed tests.
Released `webpack-isomorphic-tools@2.4.2`.

**Comment by Bartekus** [comment]
Awesome Nikolay, I agree about Node v4 and furthermore, thank you for all your work, I've got lots to learn from you good sir!

**Pull request merged**
